### ISSUE TITLE
为什么表单post请求会提示 invalid csrf token

### ISSUE THREAD

**Issue by tosim** [hubcarl/egg-vue-webpack-boilerplate#10]
get请求没问题，但是post请求会提示invalid csrf token

**Comment by liuchonggao** [comment]
@tosim 这是 eggjs 防止 csrf 攻击做的校验，token 可以在 cookie 中得到，然后 post 的时候带上 token 就可以了。

**Comment by hubcarl** [comment]
https://github.com/eggjs/egg-security  @tosim

**Comment by tosim** [comment]
原来是这样，谢谢大佬们
