### ISSUE TITLE
按照你的结构来搭建，总是报错agent can't call sendToApp before server started

### ISSUE THREAD

**Issue by liuyu322** [hubcarl/egg-vue-webpack-boilerplate#11]
![image](https://user-images.githubusercontent.com/5425933/27941721-a7b5d554-6304-11e7-865e-3d468d264eb5.png)
这是什么原因？

**Comment by ZQun** [comment]
你用的不是releases版吧？

**Comment by hubcarl** [comment]
最新master分支运行时报错？ 用的什么系统（mac or windnows)？

**Comment by hubcarl** [comment]
该问题原因是应用启动时，同时启动了webpack编译服务，应用没有启动完，发送了消息，目前问题已修复。 @liuyu322  请删除node_moduels 重新安装
