### ISSUE TITLE
less 函数，编译不通过

### ISSUE THREAD

**Issue by jerryge** [hubcarl/egg-vue-webpack-boilerplate#14]
`<style lang="less">
.ziti(@c: #C7C7C7) {
  color: @c;
}
.some {
    .ziti(#000)
}
</style>`
不用到函数的时候，less没有问题。

**Comment by hubcarl** [comment]
@jerryge  该问题需要看看

**Comment by jerryge** [comment]
@hubcarl 嗯。谢谢。看了一下easywebpack插件的loader顺序都没有问题，网上提到最多的原因是这个。

**Comment by hubcarl** [comment]
@jerryge  原因是这个？  目前测试 用@import "test.less" 方式可以， 用 style 内联方式编译出错

**Comment by jerryge** [comment]
@hubcarl 不确认定，我是谷歌了一下，别人提到的。

**Comment by jacksky007** [comment]
参照 https://github.com/vuejs/vue-loader/issues/748 来看，https://github.com/hubcarl/easywebpack/blob/master/utils/loader.js#L43 这里的loaders配置不对，我试了手动添加
```javascript
preLoaders: {
  less: 'less-loader',
}
```
是可以工作的 @hubcarl @jerryge

**Comment by hubcarl** [comment]
好的，我看一下

**Comment by hubcarl** [comment]
@jacksky007 按你的方式测试ok，已经修复less和sass style 的问题，已发布最新版本，更新最代码即可，增加了 less和sass style/import 的方式demo

**Comment by jacksky007** [comment]
@hubcarl 看了下，sass 需要
```javascript
sass: 'sass-loader?indentedSyntax'
```
另外，把 https://github.com/shama/stylus-loader 也加上吧

**Comment by hubcarl** [comment]
好，loader这一块 我找个时间(8月份）结合webpack3重写一下，支持更灵活的用户定制

**Comment by hubcarl** [comment]
针对sass已加 indentedSyntax ，stylus 也加上了 @jacksky007
