### ISSUE TITLE
Controller中下面exports.index写法ok，但是用类的写法就不支持么？

### ISSUE THREAD

**Issue by DragWeb** [hubcarl/egg-vue-webpack-boilerplate#15]
// exports.index写法ok
// exports.index = function* (ctx) {
//   yield ctx.render('index/index.js');
// };

// class写法不ok
module.exports = app => {
  class homeController extends app.Controller {
    * index() {
      console.log('app=====', app)
      yield this.ctx.render('index/index.js', this.ctx);
    }
  }

  return homeController;
};

**Comment by jacksky007** [comment]
你的示例代码不全，参照 [egg 文档](https://eggjs.org/zh-cn/basics/controller.html)，你的代码应该是这样

**Comment by DragWeb** [comment]
@jacksky007 thanks!

**Comment by DragWeb** [comment]
hi @jacksky007 controller层按下面的写法，那router.js如何写呢？
``` javascript ```
const Controller = require('egg').Controller
module.exports = class homeController extends Controller {
  * index() {
    yield this.ctx.render('index/index.js', this.ctx);
  }
};
```

**Comment by jacksky007** [comment]
@DragWeb 就你贴的内容我也不知道是啥问题，[egg 路由文档](https://eggjs.org/zh-cn/basics/router.html)是这样的
```javascript
module.exports = app => {
  app.get('/', app.controller.home.home.index)
}
```
我刚接触egg，还很不熟悉，但router.js中肯定是不能访问context的，context是请求级别的对象，而router.js是整个egg框架启动过程中使用的初始化信息，所以想在router.js用this.context方式肯定是不对的。

**Comment by DragWeb** [comment]
@jacksky007 嗯，是的，确实在router.js拿不到context,看来只看按文档方式做了，感谢感谢！
@hubcarl 建议在controller与router可以用class方式做那就更好了
