### ISSUE TITLE
开发模式下，不能直接访问在public下的静态文件

### ISSUE THREAD

**Issue by ChitaGideon** [hubcarl/egg-vue-webpack-boilerplate#16]
生产模式下 可以，
是不是webpack 需要加什么配置

**Comment by DragWeb** [comment]
config.default.js
```javascript
  exports.static = {
    prefix: '/public/',
    dir: path.join(app.baseDir, 'public')
  }
```
应该是少这个配置吧

**Comment by ChitaGideon** [comment]
@DragWeb  不少这个，
如果少这个，生产环境也应该访问不了才对

**Comment by ZQun** [comment]
确实有这个现象，http://localhost:7001/public/html/home/index.html 这个静态页面也访问不了，还有.ttf和.woff等字体文件   /public/client/font/*.ttf    /public/client/font/*.woff   @hubcarl

**Comment by ZQun** [comment]
端口是9000   访问静态console信息：net::ERR_CONNECTION_REFUSED

**Comment by hubcarl** [comment]
@ZQun  你是用最新master代码嘛？如果是最新的，是可以直接访问的。如果egg-webpack 是旧版本，本地开发模式只能通过 http://localhost:9000/public/html/home/index.html

**Comment by hubcarl** [comment]
建议看一下egg＋webpakc构建流程：http://hubcarl.github.io/easywebpack/vue/dev

**Comment by ZQun** [comment]
@hubcarl   谢谢，刚刚用了最新master没有问题！我之前用的旧版
