### ISSUE TITLE
这个怎么上正式版呢？

### ISSUE THREAD

**Issue by Yunfly** [hubcarl/egg-vue-webpack-boilerplate#19]
将例子运行start prod 和build 发现样式这些都没跟上，而且单页面应用使用客户端渲染在测试上可以，在正式也不行

**Comment by jacksky007** [comment]
@Yunfly 如果你是windows系统的话，那么跟我遇到的问题一样，是 easywebpack 里面一处路径处理的平台兼容性问题。

**Comment by hubcarl** [comment]
好的，windows问题周末我处理一下

**Comment by hubcarl** [comment]
@Yunfly  @jacksky007  Windows7 已经支持，我用虚拟机测试，两位看看

**Comment by hubcarl** [comment]
本地运行：npm start   发布：npm run build

**Comment by Yunfly** [comment]
可以了！ 感谢 @hubcarl
