### ISSUE TITLE
windows下启动报错

### ISSUE THREAD

**Issue by callmesoul** [hubcarl/egg-vue-webpack-boilerplate#24]
windows下 npm start 运行报错 
`Cannot read property 'index/index.js' of undefined`

**Comment by Eric-Zhong** [comment]
跟我的 #22  一样！

**Comment by hubcarl** [comment]
@Eric-Zhong  也是windows 10 ？

**Comment by callmesoul** [comment]
@hubcarl 是的，windows 10

**Comment by callmesoul** [comment]
#22

**Comment by callmesoul** [comment]
是不是node版本太高了？我的是最新的8.6

**Comment by Eric-Zhong** [comment]
我的是 windows 10 +  node v8.3.0 .

**Comment by hubcarl** [comment]
好的，windows10 问题我尽快修复， 如果可能，Node开发最好用mac

**Comment by hubcarl** [comment]
@Eric-Zhong @callmesoul  windows问题已修复， 请重新安装依赖验证一下，另外项目里面：
- egg-vue-webpack-boilerplate/app/web/framework/vue/entry/client-loader.js 和
- egg-vue-webpack-boilerplate/app/web/framework/vue/entry/server-loader.js 有修改 

`this.resourcePath` 改为 `this.resourcePath.replace(/\\/g, '\\\\')`
