### ISSUE TITLE
linux 环境 运行不起来

### ISSUE THREAD

**Issue by leonhu0710** [hubcarl/egg-vue-webpack-boilerplate#27]
Error: spawn easywebpack ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-vue-webpack-boilerplate@1.3.1 build: `cross-env easywebpack build prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-vue-webpack-boilerplate@1.3.1 build script.

**Comment by hubcarl** [comment]
请确认是否成功安装了cli： npm i easywebpack-cli -g

**Comment by leonhu0710** [comment]
@hubcarl 额，排查出来是 linux下 webpack没有加到环境变量中，手动加入后，报
# npm run build


> egg-vue-webpack-boilerplate@2.0.0 build /opt/woyaoquyin/front/web
> cross-env easywebpack build prod

internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1016:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at Object.exports.spawn (child_process.js:491:9)
    at spawn (/opt/woyaoquyin/front/web/node_modules/_cross-spawn@5.1.0@cross-spawn/index.js:17:18)

**Comment by leonhu0710** [comment]
@hubcarl 大神帮我看看

**Comment by leonhu0710** [comment]
![Uploading image.png…]()

**Comment by leonhu0710** [comment]
@hubcarl @willworks @HiuYanChong 大神们，这个框架适合linux环境吗？看介绍 只说 master 分支为 Webpack2 稳定版本, 支持Mac/Windows, 建议线上使用.

**Comment by hubcarl** [comment]
- @leonhu0710  线上部署与webpack没有关系， webpack只在打包构建期间用到，项目运行期间用不到，你需要保证能够正常构建 即可
- Webpack2 稳定版本 指的是目前支持Webpack2，支持mac和windows， Webpack3 还在适配中

**Comment by hubcarl** [comment]
@leonhu0710  安装 ｀ npm i easywebpack-cli -g｀后，  你检查一下 easywebpack 命令是否ok， 如果ok，直接easywebpack build prod 运行一下构建试试， 去掉cross-env

**Comment by leonhu0710** [comment]
@hubcarl 好的，谢谢，我试试

**Comment by leonhu0710** [comment]
npm i easywebpack-cli -g   在linux安装后提示安装成功，但是 加不进环境变量？请问怎么弄呢

**Comment by hubcarl** [comment]
直接 easywebpack build prod  能运行不？

**Comment by leonhu0710** [comment]
运行不了， 好像 安装 easywebpack 时候就 有问题，WARN node unsupported "node@v8.1.2" is incompatible with imagemin-webpack-plugin@1.5.2 › imagemin-jpegtran@5.0.2 › jpegtran-bin@3.2.0 › bin-build@2.2.0 › download@4.4.3 › got@^5.0.0, expected node@>=0.10.0 <7
...............
platform unsupported webpack-tool@3.0.0 › webpack@3.5.6 › watchpack@1.4.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)

-----
linux下我需要安装低一点的 node版本吗？

**Comment by hubcarl** [comment]
这个骨架是支持node4++，你可以用node6 稳定版本  这个报错有个issue说不影响webpack使用：https://github.com/webpack/webpack/issues/2722

**Comment by hubcarl** [comment]
另外， 你线上启动运行时 ，可以执行： npm install --production，  不安装 devDependencies

**Comment by leonhu0710** [comment]
我本地部署问题，和框架本身无关
