### ISSUE TITLE
Cannot find module 'webpack/lib/RequestShortener'

### ISSUE THREAD

**Issue by wengcd** [hubcarl/egg-vue-webpack-boilerplate#28]
`npm i`之后警告如下

```
npm WARN stats-webpack-plugin@0.6.1 requires a peer of webpack@^1.0||^2.1.0-beta||^2.2.0-rc but none is installed. You must install peer dependencies yourself.
```
```
npm WARN directory-named-webpack-plugin@2.2.3 requires a peer of webpack@>=2.2.0 but none is installed. You must install peer dependencies yourself.
```
```
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
```
忽略之后报如下错误
`Cannot find module 'webpack/lib/RequestShortener'`

Node 版本 v6.9.2

**Comment by hubcarl** [comment]
@wengcd  删除node_modules 重新安装一下

**Comment by wengcd** [comment]
试过了

**Comment by wengcd** [comment]
重新 git pull 了一下，现在正常了

**Comment by wengcd** [comment]
> 现在有新的问题，安装第三方会报如下错误，而且装不上

<img width="570" alt="wx20170922-111120 2x" src="https://user-images.githubusercontent.com/2403371/30727919-e1b096b8-9f86-11e7-94b5-9245df882e39.png">

**Comment by wengcd** [comment]
> 上述问题需通过删除 `package-lock.josn` 来解决
> `npm run build` 会产生新问题
![wx20170922-143820](https://user-images.githubusercontent.com/2403371/30732245-359d1806-9fa4-11e7-83a5-0ab0599a5ca9.png)

**Comment by hubcarl** [comment]
安装npm插件不要su do

**Comment by hubcarl** [comment]
重新拉一下代码，然后删除node_modules，再安装一下npm install试试

**Comment by hubcarl** [comment]
看一下node_modules下easywebpack（3.2.6）和easywebpqck-vue（3.2.0）版本多少？

**Comment by hubcarl** [comment]
@wengcd  该问题已修复，先关掉，如果还有问题，可以再沟通。
