### ISSUE TITLE
windows环境npm start报错

### ISSUE THREAD

**Issue by z-ak** [hubcarl/egg-vue-webpack-boilerplate#3]
![image](https://cloud.githubusercontent.com/assets/24920470/26445274/326a7380-4172-11e7-87ce-0f18a0c28448.png)

windows系统上npm start报以上截图的错误。麻烦您帮忙看下~

**Comment by hubcarl** [comment]
问题原因是因为window下面路径处理有问题，目前已修正。 目前master分支最新代码支持mac和windows平台，本次修改升级了easywebpack，egg-webpack-vue , egg-view-vue-ssr。

**Comment by z-ak** [comment]
已在windows平台上测试，可以正常打包运行。十分感谢～
