### ISSUE TITLE
还需完善吧

### ISSUE THREAD

**Issue by chuchur** [hubcarl/egg-vue-webpack-boilerplate#30]
mac 环境 ,node v8.5

第一步 npm install easywebpack-cli -g
接着 用 easywebpack 脚手架, 一路down...下一步走完..
然后npm i   完毕. 
最后 npm start 
居然没跑起来..
![image](https://user-images.githubusercontent.com/4814173/30896875-d3af34a8-a318-11e7-9290-a227e9feba17.png)
![image](https://user-images.githubusercontent.com/4814173/30896890-e602ea6e-a318-11e7-8584-3b4703b68ade.png)

加油..

**Comment by hubcarl** [comment]
@chuchur  缺少了.babelrc 文件，在项目根目录下面添加 一下， 然后加上： 

{
  "presets": ["env"],
  "plugins": [
    "add-module-exports",
    "transform-object-rest-spread",
    "syntax-dynamic-import",
    "transform-object-assign"
  ],
  "comments": false
}

**Comment by hubcarl** [comment]
@chuchur  .babelrc 问题已修复， 请重新安装 npm install easywebpack-cli -g， 然后在 easy init
