### ISSUE TITLE
Can't resolve 'vertx' in '/node_modules/es6-promise/dist'

### ISSUE THREAD

**Issue by dbsg** [hubcarl/egg-vue-webpack-boilerplate#34]
在web/page/story 文件夹下面新建两个vue文件，build之后会报警

**Comment by hubcarl** [comment]
@dbsg  https://github.com/stefanpenner/es6-promise/issues/100

在 webpack.config.js 里面加上测试一下

```
const EasyWebpack = require('easywebpack-vue');
const webpack = EasyWebpack.webpack;
plugins:{
   vertx: new webpack.IgnorePlugin(/vertx/),
}
```

**Comment by dbsg** [comment]
@hubcarl 您好，在配置文件加了之后还是会出现WARNING in ./node_modules/es6-promise/dist/es6-promise.js
    Module not found: Error: Can't resolve 'vertx' in '/Users/dbsg/WebstormProjects/page_8pig_com/node_modules/es6-promise/dist'

**Comment by hubcarl** [comment]
@dbsg 该问题解决没？ 如果没有，可以提供一下可重现的demo

**Comment by hubcarl** [comment]
该问题先关闭了，如果还有问题，可以再找我，我再专门跟进一下。

**Comment by dbsg** [comment]
问题解决了，不好意思啊，之前没有看到回复，麻烦了。
