### ISSUE TITLE
__INITIAL_STATE__ 优先于options.data()

### ISSUE THREAD

**Issue by feix760** [hubcarl/egg-vue-webpack-boilerplate#35]
https://github.com/hubcarl/egg-vue-webpack-boilerplate/blob/3593fe9018195e7f5b38a1d9cdedb5a20ac7007f/app/web/framework/vue/entry/client.js#L22

这个地方这样是不是更合理

```javascript
options.data = Object.assign(options.data && options.data(), window.__INITIAL_STATE__);
```

`__INITIAL_STATE__`应该覆盖data的数据

**Comment by hubcarl** [comment]
我认为两种都可以，这个你根据实际情况可修改

**Comment by ltinyho** [comment]
https://github.com/hubcarl/egg-vue-webpack-boilerplate/blob/b8b3eaf042d02173ce8b72d25e3aef21b8747aef/app/web/framework/vue/app.js#L23
这样服务端获取到的数据又被本地覆盖了，需要重新获取，是否调整一下顺序
```
options.store.replaceState(Object.assign({}, options.store.state, App.data()));
```
