### ISSUE TITLE
怎么改变启动服务后，弹出浏览器的7001端口

### ISSUE THREAD

**Issue by wen-dong** [hubcarl/egg-vue-webpack-boilerplate#39]
启动服务后，会打开浏览器，这时候访问的是7001端口，但是却不是我配置的，这应该怎么改呢？

**Comment by hubcarl** [comment]
请配置 process.env.PORT=xxx， 这个端口 将做完应用启动的端口(${app_root}/index.js 和 开发期间自动打开的端口。

本地开发，你可以修改 package.json 里面的script 脚本。

```
"start": "node index.js"
```

改为 

```
"start": "cross-env PORT=8888 node index.js"
```

或者命令行直接增加参数
```
>PORT=8888 npm start
```
