### ISSUE TITLE
egg locals 和 vuex state 问题

### ISSUE THREAD

**Issue by meidea** [hubcarl/egg-vue-webpack-boilerplate#41]
https://github.com/hubcarl/egg-vue-webpack-boilerplate/blob/f2659566ac736c1fe99404cdb68081db96b46d73/app/web/framework/vue/app.js#L23
这一块改成这样是不是好些，防止vuex的默认的state丢失
`options.store.replaceState(Object.assign(options.store.state, App.data()));`

同理
https://github.com/hubcarl/egg-vue-webpack-boilerplate/blob/f2659566ac736c1fe99404cdb68081db96b46d73/app/web/framework/vue/app.js#L47
防止locals丢失
`context.state = Object.assign(options.store.state, context.state);`

**Comment by hubcarl** [comment]
@meidea  这个可以有
