### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by webzhd** [hubcarl/egg-vue-webpack-boilerplate#42]
![image](https://user-images.githubusercontent.com/23025883/32815971-8aed72a2-c9f1-11e7-9d3a-a8c51ccf900e.png)
请问一下是什么原因

**Comment by webzhd** [comment]
本地运行正常

**Comment by hubcarl** [comment]
PROD模式打包时，开启了压缩， Webpack 默认 uglify-js 是不支持ES6代码的压缩的，解决的办法三种方式：

第一种是在 webpack.config.js  的增加如下配置试试

loaders:{
  babel:{
    exclude:[] // 默认是排除 node_modules
  }
}

第二种是直接找出node_modules  es6的写法的引用的模块，移除调，用其它模块

第三种

在package.json的devDependencies中加入如下依赖，然后重新执行一遍 npm install 试试

"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony


第一种和第三种你可以试试，如果有问题，给一个可以重新的github demo地址

@webzhd

**Comment by webzhd** [comment]
我项目中使用了大量的ES6，上面三个方法暂时无法解决我的问题

**Comment by hubcarl** [comment]
项目中es6 没有问题， node_module  里面有es6 会有这个问题

**Comment by webzhd** [comment]
十分感谢，现在已经解决了
