### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by GoBrianGo** [hubcarl/egg-vue-webpack-boilerplate#43]
1、打包后的静态文件的路径是写死的吗？（public）
2、为什么打包的文件会这么大，我什么都还没写都有1m多。

**Comment by GoBrianGo** [comment]
![image](https://user-images.githubusercontent.com/9709359/33160596-9e6885de-d058-11e7-8d19-917946c76287.png)
打包的这个publicPath是在easywebpack写死的，如果我需要改呢？

**Comment by GoBrianGo** [comment]
知道了，在webpack.config.js中定义

**Comment by hubcarl** [comment]
打包有三种模式，开发模式(dev)，测试模式(test)，线上模式(prod).

config.env : 目前支持 dev, test, prod 三种环境, 默认 dev

dev : 开启热更新(config.hot=true), js (config.miniJs=false), image (config.miniImage=false), css (config.miniCss=false) 不压缩, 不 hash (confg.hash=false)
test : 开启热更新(config.hot=false), js (config.miniJs=false), image (config.miniImage=false), css (config.miniCss=false) 不压缩, hash (config.hash=true)
prod : 开启热更新(config.hot=false), js (config.miniJs=true), image (config.miniImage=true), css (config.miniCss=true) 压缩, hash (config.hash=true)
本地开发(dev)时, 为了支持 css hot reload, css 样式必须 inline, 所以默认构建是全部 inline css (config.cssExtract=false), test 和 prod 环境时, css是独立出css文件(config.cssExtract=true)

API文档：http://hubcarl.github.io/easywebpack/webpack/config/
