### ISSUE TITLE
服务端渲染问题

### ISSUE THREAD

**Issue by zhengyu1996** [hubcarl/egg-vue-webpack-boilerplate#44]
引用一些外部插件时，总是会warning 推荐我使用renderClient来进行渲染。 并且报一个document is not defined的错误。 请问一下这是什么原因呢

**Comment by hubcarl** [comment]
那是因为你引入的外部组件不支持服务端渲染，也就是代码里面直接调用了浏览器里面的API，比如document，window等

**Comment by huangche007** [comment]
@zhengyu1996 因为node环境没有document对象之类的

**Comment by longmore** [comment]
如何不让部分组件服务端渲染？避免出现一些组件里面包含document 或 navigator的问题

**Comment by hubcarl** [comment]
你这些操作放到 mouted里面去或者自己判断是Node 端还是 Browser端
