### ISSUE TITLE
单页应用vue-router命名视图在子组件内创建不生效

### ISSUE THREAD

**Issue by ZQun** [hubcarl/egg-vue-webpack-boilerplate#46]
单页应用Vue-router无法在子组件内添加<router-view name="xxx"></router-view>
router路由components 没有效果显示

router.js
`
{
            path: '/',
            components: {
                default: ListView,
                demo: () => import('./demo.vue')
                // demo: demoTest
            }
        }
`

复现地址：
https://github.com/ZQun/egg-vue-webpack-boilerplate/commit/5260f087aefc3a59040e8f79adf4d6c4949ca75b

**Comment by hubcarl** [comment]
@ZQun  该问题已初步修复，具体请见  master 最新分支  dynamic.vue 和 egg-vue-webpack-boilerplate/app/web/component/app/router.js

**Comment by ZQun** [comment]
@hubcarl 在项目中测试了，命名视图和嵌套路由都可以用了！原项目中把easywebpack-vue升级到了3.5.1版本

**Comment by hubcarl** [comment]
https://zhuanlan.zhihu.com/p/32887257
