### ISSUE TITLE
在服务端渲染时候新建page下的子项 修改代码在windows上不能触发热更新mac正常

### ISSUE THREAD

**Issue by shenjianzch** [hubcarl/egg-vue-webpack-boilerplate#51]
在服务端渲染时候新建page下的子项 修改代码在windows上不能触发热更新mac正常，按了保存啥都不做

**Comment by hubcarl** [comment]
好的，该问题已定位是bug，具体原因待查

**Comment by Testerdana** [comment]
@shenjianzch  该问题已修复，是windows 路径处理问题，目前已发布 3.5.15 版本，请重新安装 easywebpack 依赖，确保 版本是 3.5.15
