### ISSUE TITLE
同一界面中，多个模板，使用不同的渲染方式

### ISSUE THREAD

**Issue by klk2** [hubcarl/egg-vue-webpack-boilerplate#52]
你好，在vue中，怎么实现：同一界面中，多个模板，使用不同的渲染方式。
假设在A页面中，a模板用服务端渲染，a2模板用客户端渲染

**Comment by klk2** [comment]
我在mounted后，通过调用vue异步组件的方式解决了。
A页面使用服务端渲染，mounted之后，再注册模板。

**Comment by hubcarl** [comment]
@klk2  用 import 方式，见最新master dynamic.vue
