### ISSUE TITLE
vue 多页面服务端渲染 后端路由控制 父组件引入子组件出现较长时间白屏

### ISSUE THREAD

**Issue by HuangXiZhou** [hubcarl/egg-vue-webpack-boilerplate#59]
您好，我使用的是 feature/green/multi 这个分支的模板，现在出现了父组件引入子组件后 进入该页面时出现较长时间白屏刷新，使用异步引入组件也无法解决问题，请问有什么较好的方法么

**Comment by hubcarl** [comment]
请提供github demo 看看，另外你用发布模式看看
