### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cswww** [hubcarl/egg-vue-webpack-boilerplate#61]
![2018-03-13 11 07 24](https://user-images.githubusercontent.com/30970064/37320458-cf0759d4-26ae-11e8-8dd7-4fde5cd452e1.png)
按照教程：npm install
npm run dev
出现这个页面

**Comment by cswww** [comment]
![2018-03-13 11 31 41](https://user-images.githubusercontent.com/30970064/37321458-69e1fd52-26b3-11e8-9418-e3da4b4b355d.png)

**Comment by hubcarl** [comment]
@cswww eslint 禁用试试，你这个是什么系统？

```
// webpack.config.js
module.exports = {
 loaders:{
  eslint: false
 }
}
```

**Comment by cswww** [comment]
可以了 我的mac系统 不过这样就没有eslint检查了吧

**Comment by hubcarl** [comment]
@cswww  你 node 版本多少？建议用 8.10.0 版本， 你可以 npm run lint 看看是否可以

**Comment by cswww** [comment]
9.2.0的版本

**Comment by cswww** [comment]
还有个问题 我想安装egg-script 也装不上去 这个好像是用index启动的

**Comment by cswww** [comment]
![2018-03-13 11 46 40](https://user-images.githubusercontent.com/30970064/37352738-e2c63818-2718-11e8-995b-e2064edb1650.png)

**Comment by hubcarl** [comment]
你把 egg-script 依赖写到依赖里面，然后重新全部安装，npm有时候会出现这种情况，和哪种启动没关系。这里用index.js 启动是让大家知道入口代码在哪里，比较直观。

**Comment by cswww** [comment]
好的 谢谢
