### ISSUE TITLE
怎么设置使用localhost打开浏览器

### ISSUE THREAD

**Issue by meidea** [hubcarl/egg-vue-webpack-boilerplate#63]
编译完成后，想使用localhost或者127.0.0.1打开浏览器，这个怎么设置呢？

怎么强制使用chrome，而不是系统默认的浏览器？

**Comment by hubcarl** [comment]
@meidea  想使用localhost或者127.0.0.1打开浏览器:

在 config/config.local.js 里面配置

```js
exports.webpack = {
    browser: 'http://localhost:7001'
};
```

你的骨架是哪个版本？ 最新的版本已经默认添加了这个

**Comment by hubcarl** [comment]
只能把chrome 设置为默认浏览器

**Comment by meidea** [comment]
好的，多谢；我的已经用于生产环境，所以不敢随便升级
