### ISSUE TITLE
Tapable.plugin已经弃用，改为在.hooks上使用新API

### ISSUE THREAD

**Issue by ZQun** [hubcarl/egg-vue-webpack-boilerplate#64]
日志提示：Tapable.plugin已经弃用，改为在.hooks上使用新API

**Comment by hubcarl** [comment]
这个是warning，不影响使用，暂时没有查出是哪个插件输出的，需要继续排查

**Comment by hubcarl** [comment]
已修复：https://github.com/hubcarl/webpack-tool/blob/master/CHANGELOG.md
