### ISSUE TITLE
config.local.js修改端口无效

### ISSUE THREAD

**Issue by fengjx** [hubcarl/egg-vue-webpack-boilerplate#68]
```javasceipt
-- config/config.local.js，将9000和9001改成8000和8001

  [7001, 8000, 8001].forEach(port => {
    domainWhiteList.push(`http://localhost:${port}`);
    domainWhiteList.push(`http://127.0.0.1:${port}`);
    domainWhiteList.push(`http://${localIP}:${port}`);
  });
```

报错信息
![image](https://user-images.githubusercontent.com/4881720/38469894-5b6906c2-3b8e-11e8-90e4-d1c973799f14.png)

操作系统：macOS

node版本: v9.10.0

**Comment by hubcarl** [comment]
@fengjx 你这个是端口被占用了 可以 npx easy kill 杀掉，换端口请看 多项目开发时, 端口占用问题：http://hubcarl.github.io/easywebpack/webpack/problem/

**Comment by zqcloveping** [comment]
@hubcarl 开发时经常出现因为代码的部分错误导致进程退出，但是端口依然被占用。每次都得手动啥端口去关闭。运行npm run kill-mac又一直报错。不知道有没有什么好的方案在进程崩溃后自己kill掉相关的端口占用

**Comment by zqcloveping** [comment]
还有每次启动后都会报这个错误 ERROR 96914 [-/::1/-/9ms GET /public/js/vendor.js] nodejs.ECONNRESETError: socket hang up  
@hubcarl  麻烦您给解答一下

**Comment by hubcarl** [comment]
会经常？ 这种情况出现比较少，出现了 可以 npx easy kill 杀掉

**Comment by zybieku** [comment]
![image](https://user-images.githubusercontent.com/15903330/91867665-79c68100-eca6-11ea-99fd-8bb46260203d.png)
easy init的项目 ,啥都没弄 这端口就起不来.npx easy kill掉也没官用,怎么修改端口,默认启动三个端口,没看到修改的地方
