### ISSUE TITLE
你好，当配置externals 为vue 的时候服务器端渲染失效

### ISSUE THREAD

**Issue by yudawei1230** [hubcarl/egg-vue-webpack-boilerplate#69]
场景是这样的，我想vue以script cdn的形式导入页面的时候，既打包客户端代码时不引入vue部分的代码改为cdn的方式引入时，服务器端渲染就不成功了，截图如下，想问问有没有什么办法能解决下
![3bd39407-5fa4-f0b2-a15a-a0504c601d3f](https://user-images.githubusercontent.com/15976653/38547001-b082d07c-3ce0-11e8-9362-1e1cf7d8564d.png)
![1da16d88-c660-6adf-1d27-77eae55037bd](https://user-images.githubusercontent.com/15976653/38547005-b2723abc-3ce0-11e8-854e-2eb9b887fc37.png)

**Comment by yudawei1230** [comment]
还有，我还想问下，为什么在生产模式下 console.log 会失效，只有在dev下才能打印日志

**Comment by hubcarl** [comment]
发布模式会压缩，console会移除
