### ISSUE TITLE
服务端渲染模式 import 中的文件包含 window 对象报错

### ISSUE THREAD

**Issue by ryan-hung** [hubcarl/egg-vue-webpack-boilerplate#70]
你好，我在 egg + vue 服务端渲染的模版下引入了  lib-flexible 库处理移动端适配的问题  因为该库中需要是用到 window 对象，请求页面时 node 控制台会打印 "找不到 window 对象" 且 Layout 组件中的 slot 也无法完成替换，请问该如何解决这个问题？

**Comment by hubcarl** [comment]
这个组件包不支持ssr，需要你判断一下只在客户端渲染

**Comment by hubcarl** [comment]
Vue SSR 组件加载:  https://zhuanlan.zhihu.com/p/36233639
