### ISSUE TITLE
4.0.1 仓库代码 client页面白屏

### ISSUE THREAD

**Issue by shindoujay** [hubcarl/egg-vue-webpack-boilerplate#72]
egg-vue-webpack-boilerplate:4.0.1
node 版本:v8.9.4
os 版本:macOS 10.12.6

clone 仓库代码
运行之后 
Server-Render 页面正常显示
Client-Render 页面白屏
![screen shot 2018-04-24 at 7 02 30 am](https://user-images.githubusercontent.com/6114216/39157467-814ed0aa-478d-11e8-869a-3d07ed3ffcf7.png)

**Comment by shindoujay** [comment]
config.local.js中加入如下代码即可，但不知道原因是？以及会不会影响之后发布模式？
`  exports.webpack = {
    proxy: {
      host: 'http://192.168.199.249:9000'//此处为本机ip地址，127.0.0.1或localhost 都不行
    }
  };`

**Comment by hubcarl** [comment]
@shindoujay 不会影响发布模式，这个插件直接本地才会用到

**Comment by hubcarl** [comment]
@shindoujay 白屏问题看一下 chrome dev tool 控制台
