### ISSUE TITLE
iview样式文件引入时,重复打包处理

### ISSUE THREAD

**Issue by hexingnmxy** [hubcarl/egg-vue-webpack-boilerplate#75]
1.在client.js中引入iview的样式文件(如下图),npm run build时会在每个页面文件中重复打包进去(如下图),工程项目中如何配置将公共css样式抽离打包成一个单独的css文件?
![image](https://user-images.githubusercontent.com/22442909/40534000-1ba1fe18-6037-11e8-9a29-a256e30860bb.png)
![image](https://user-images.githubusercontent.com/22442909/40534051-524bbc2e-6037-11e8-9fba-cbb37852ca6b.png)
2.换个方法处理这个问题,在公用的html中引入iview(如下图),但iview.css中引用的字体图标应该处理?
![image](https://user-images.githubusercontent.com/22442909/40534418-9065fb68-6038-11e8-8a90-5bb4e35eebc9.png)
![image](https://user-images.githubusercontent.com/22442909/40534441-9fc72398-6038-11e8-9d67-12fdebc30907.png)

**Comment by ZQun** [comment]
直接在app.vue引入呢

```
<template>
    <app-layout>
        <transition name="fade" mode="out-in">
            <router-view></router-view>
        </transition>
    </app-layout>
</template>

<script type="text/ecmascript-6">
    import 'babel-polyfill';
    import Vue from 'vue';
    import iView from 'iview';
    import 'iview/dist/styles/iview.css';
    import 'asset/css/reset.css';
    import local from 'asset/js/local-storage';
    import router from './router';

    Vue.use(iView);

    router.beforeEach((to, from, next) => {
        iView.LoadingBar.start();
        next();
    });

    router.afterEach(route => {
        iView.LoadingBar.finish();
    });

    export default {
        data() {
            return {

            }
        },
        props: {},
        components: {},
        computed: {},
        methods: {},
        mounted() {}
    }
</script>

<style lang="stylus" rel="stylesheet/stylus">
    &.fade-enter-active, &.fade-leave-active
        transition: all 0.3s ease
    &.fade-enter, &.fade-leave-active
        opacity: 0
</style>
```

**Comment by hubcarl** [comment]
贴一下 webpack.config.js 配置看看，默认是提取所有 entry的 公共 css

commonsChunk: {
minChunks: function (module, count) {
  const resource = module.resource
  // 以 .css 结尾的资源，重复 require 大于 指定次数，比如 2次
  return resource && /\.css$/.test(resource) && count > 1;
}
}

**Comment by hubcarl** [comment]
link 那里为什么重复引入 ivew.css
