### ISSUE TITLE
vue-route 设置base时，匹配不到组件

### ISSUE THREAD

**Issue by ltinyho** [hubcarl/egg-vue-webpack-boilerplate#76]
复现仓库  https://github.com/ltinyho/egg-vue-webpack-boilerplate/tree/feature/green/spa

我修改的代码
app/route.js
```
  app.get('/mm(/.+)?', app.controller.app.index);
```
web/component/app/route.js 
将`base:'/'` 改为了 `base:'/mm/'`

初步找到原因是在`app/web/framework/app.js`中`App.server`
```
  options.router.push(context.state.url);
   const matchedComponents = options.router.getMatchedComponents();
```
匹配不到组件，
我做了一下修改
```
  options.router.push(context.state.url.replace('/mm',''));
```
能匹配到组件，但是 组件中`preFetch`请求到的数据在`store`中设置不到。

**Comment by ltinyho** [comment]
```
 await this.ctx.render('app/app.js', {
      url: this.ctx.url.replace(/\/mm/, ''),
    });
```

需要将`context.url`修改为` url: this.ctx.url.replace(/\/mm/, '')`,跟在 `app/web/framework/app.js`设置 `options.router.push(context.state.url.replace(/\/mm/, '));`是一样的意思。

**Comment by pbbisme** [comment]
@ltinyho 为什么我下载你改的也是组件中preFetch请求到的数据在store中设置不到，官方的骨架项目也不行，在组件里面删掉beforeMount 只保留 preFetch  的话，页面会一闪而过然后就没数据了，store也没设置到数据

**Comment by ltinyho** [comment]
那是因为  [看下这里的逻辑](https://github.com/ltinyho/egg-vue-webpack-boilerplate/blob/feature%2Fgreen%2Fspa/app/web/framework/vue/app.js#L19)，数据被覆盖了，需要自己改一下覆盖的顺序

**Comment by pbbisme** [comment]
@ltinyho 谢谢，改了会有其他问题，能力有限，我还是去玩官方标配去
