### ISSUE TITLE
如何引入静态的js文件

### ISSUE THREAD

**Issue by lcsoftware** [hubcarl/egg-vue-webpack-boilerplate#78]
我想引入百度的ueditor组件，请问题ueditor的库文件需要入在哪个目录下，如何引用到项目，放在public目录下开发阶段是没有问题的，但打包发布就不行了，因为easy run clean 会删除public下的静态目录  。

**Comment by shenjianzch** [comment]
可以指定静态资源目录 然后引就好了

**Comment by hubcarl** [comment]
@lcsoftware  可以 import 引入或者 cdn 链接， 另外可以看看 egg-static
