### ISSUE TITLE
怎么生成可以执行的html文件 像vue-cli样的打包有么

### ISSUE THREAD

**Issue by shenjianzch** [hubcarl/egg-vue-webpack-boilerplate#79]
怎么生成可以执行的html文件 像vue-cli样的打包有么 因为想单独拿出去打包成app 混合用 所以有这需求

**Comment by hubcarl** [comment]
@shenjianzch  https://github.com/hubcarl/easywebpack-cli-template   或者 https://github.com/hubcarl/easywebpack-multiple-html-boilerplate  通过 easywebpack-cli 初始化
