### ISSUE TITLE
国际化支持方案

### ISSUE THREAD

**Issue by ihubcode** [hubcarl/egg-vue-webpack-boilerplate#83]
服务端渲染，用vue-i18next，但总是会报错，比如" window is not defined"，“i18n is not defined”等.....

**我尝试在filter中写，也会报找不到i18n，以下是过滤器方案：**

i18n.js封装：
```
import Vue from 'vue';
import i18next from 'i18next';
import VueI18Next from '@panter/vue-i18next';
import message from 'asset/locales';
...
Vue.use(VueI18Next);
// 多语言配置
i18next.init({
  lng: currentLang,
  resources: {
    'zh-cn': { translation: message.cn },
    en: { translation: message.en }
  }
});
const i18n = new VueI18Next(i18next);

export default i18n;
```

/framework/vue/filter/index.js

```
import Vue from 'vue';
import i18n from '../locales/i18n';

Vue.filter('t', value => {
  if (!value) return '';
  return i18n.t(value);
});
```

直接在组建中使用，会报错找不到i18next：

footer.vue

```
...省略
<div>{{ 'message' | t }}</div>

... 省略
```

**想无缝对接i18n，能否给个方案出来，供参考？**

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/44838298-6115d180-ac6e-11e8-882f-12831b7560d3.png)

**Comment by ihubcode** [comment]
嗯，感谢 @hubcarl 能抽时间及时响应此issue，虽然自己之前已经解决，但不是通过middleware方式处理，你的这种方式，代码及结构确实优雅规范很多，值得借鉴。
