### ISSUE TITLE
easywebpack里面怎样加入loaders？

### ISSUE THREAD

**Issue by ZQun** [hubcarl/egg-vue-webpack-boilerplate#9]
想添加.woff .eot .ttf  等字体加载，要怎样引用？

loaders: [
      {
        test   : /\.woff|\.woff2|\.svg|.eot|\.ttf/,
        loader : 'url?prefix=font/&limit=10000'
      }
    ]

**Comment by ZQun** [comment]
OK   研究出来啦，在constructor加入：addLoader();

this.addLoader(/\.woff$/,'url-loader?limit=10000&mimetype=application/font-woff');
this.addLoader(/\.ttf$/,'url-loader?limit=10000&mimetype=application/octet-stream');
this.addLoader(/\.eot$/,'file-loader');
this.addLoader(/\.svg$/,'url-loader?limit=10000&mimetype=image/svg+xml');

**Comment by DragWeb** [comment]
@ZQun 请问‘ constructor’是指什么位置？我也遇到这个问题不知在哪加入

**Comment by DragWeb** [comment]
知道了。。。在create方法里面加入即可
