### ISSUE TITLE
package.json 下的node-sass 无法安装

### ISSUE THREAD

**Issue by 54yuri** [hubcarl/egg-vue-webpack-boilerplate#95]
平台： windows 10, 
其他：python 3

默认package.json 下的node-sass 和sass-loader 无法在windows和python3的环境下安装，各种报错，node-sass即使单独安装都坑巨多，package.json 附带上它感觉带了个大包袱。
能否在这个boilerplate当中去掉sass依赖，或者在readme.md当中说明注意事项，去掉node-sass后可以使用npm i

**Comment by hubcarl** [comment]
可以去掉，你直接去掉就行 https://www.yuque.com/hubcarl/easywebpack/problem

**Comment by 54yuri** [comment]
好的，多谢，已经解决

**Comment by hubcarl** [comment]
master sass 样式已改写 css，且已去掉 sass，自己根据需要引入
